name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]
        ts-project: [tsconfig.json]

    env:
      TS_NODE_PROJECT: ${{ matrix.ts-project }}

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm cache clean --force
      - run: npm ci
      - run: npm run lint
      - run: npm run build
